apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: "localhost:6000"
  - name: redisPassword
    secretKeyRef:
      name: redis
auth:
    secretStore: demosecrets