kind: Service
apiVersion: v1
metadata:
  name: aspnetcoresecrets
  labels:
    app: aspnetcoresecrets
spec:
  selector:
    app: aspnetcoresecrets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcoresecrets
  labels:
    app: aspnetcoresecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcoresecrets
  template:
    metadata:
      labels:
        app: aspnetcoresecrets
        aadpodidbinding: reads-vault
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: aspnetcoresecrets
        dapr.io/port: "80"
    spec:
      containers:
        - name: aspnetcoresecrets
          image: cmendibl3/aspnetcoresecrets:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
