apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: readings-input
spec:
  type: bindings.azure.eventhubs
  metadata:
    - name: connectionString
      value: Endpoint=sb://<EVENT HUBS NAME>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<EVENTHUBS KEY>;EntityPath=<EVENTHUBS ENTITY NAME>
    - name: consumerGroup
      value: "group1"
    - name: storageAccountName
      value: "<STORAGE ACCOUNT NAME>"
    - name: storageAccountKey
      value: "<STORAGE ACCOUNT KEY>"
    - name: storageContainerName
      value: "<STORAGE CONTAINWER NAME>"
